// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNAKBqkTPZHrKmPYmWJP0f1jTHm2y8S8o',
    appId: '1:1015121895633:web:d4961bcf847178fe5d65f0',
    messagingSenderId: '1015121895633',
    projectId: 'flagss-manager',
    authDomain: 'flagss-manager.firebaseapp.com',
    storageBucket: 'flagss-manager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb951_y--T6bWt7IaMpvqs6Qcbg8YXgJg',
    appId: '1:1015121895633:android:8b459223e843e97a5d65f0',
    messagingSenderId: '1015121895633',
    projectId: 'flagss-manager',
    storageBucket: 'flagss-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAizknAuMF_i0lIql2d8J_d_jLW0wHPZz4',
    appId: '1:1015121895633:ios:4ea6b53b353209d15d65f0',
    messagingSenderId: '1015121895633',
    projectId: 'flagss-manager',
    storageBucket: 'flagss-manager.firebasestorage.app',
    iosBundleId: 'com.example.flagsManager',
  );
}
